version: "3.9"

services:
  db:
    image: postgres:alpine
    container_name: postgres_sgbd
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data